# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sim_clk_gen_0_0/design_1_sim_clk_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sim_clk_gen_0_0 || ORIG_REF_NAME==design_1_sim_clk_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CORE_0_0/design_1_CORE_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CORE_0_0 || ORIG_REF_NAME==design_1_CORE_0_0} -quiet] -quiet

# XDC: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ip_repo/IP_tester/IP_tester.gen/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0_ooc.xdc

# XDC: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ip_repo/IP_tester/IP_tester.gen/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ip_repo/IP_tester/IP_tester.gen/sources_1/bd/design_1/design_1_ooc.xdc
