LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

PACKAGE FOC_types IS

    TYPE type_PWM_register IS ARRAY (INTEGER RANGE <>) OF signed (12 DOWNTO 0);

END FOC_types;

PACKAGE BODY FOC_types IS

END PACKAGE BODY FOC_types;