# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/BRAM_SIN/BRAM_SIN.xci
# IP: The module: 'BRAM_SIN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ip_repo/FOC_BLDC/FOC_BLDC.gen/BRAM_SIN/ip/BRAM_SIN/BRAM_SIN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_SIN'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: ip/BRAM_SIN/BRAM_SIN.xci
# IP: The module: 'BRAM_SIN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ip_repo/FOC_BLDC/FOC_BLDC.gen/BRAM_SIN/ip/BRAM_SIN/BRAM_SIN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_SIN'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
