# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ebit_z7010.srcs/sources_1/bd/ebit_z7010_top/ip/ebit_z7010_top_axi_gpio_0_5/ebit_z7010_top_axi_gpio_0_5.xci
# IP: The module: 'ebit_z7010_top_axi_gpio_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ebit_z7010.gen/sources_1/bd/ebit_z7010_top/ip/ebit_z7010_top_axi_gpio_0_5/ebit_z7010_top_axi_gpio_0_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebit_z7010_top_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ebit_z7010.gen/sources_1/bd/ebit_z7010_top/ip/ebit_z7010_top_axi_gpio_0_5/ebit_z7010_top_axi_gpio_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebit_z7010_top_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ebit_z7010.gen/sources_1/bd/ebit_z7010_top/ip/ebit_z7010_top_axi_gpio_0_5/ebit_z7010_top_axi_gpio_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebit_z7010_top_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ebit_z7010.srcs/sources_1/bd/ebit_z7010_top/ip/ebit_z7010_top_axi_gpio_0_5/ebit_z7010_top_axi_gpio_0_5.xci
# IP: The module: 'ebit_z7010_top_axi_gpio_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ebit_z7010.gen/sources_1/bd/ebit_z7010_top/ip/ebit_z7010_top_axi_gpio_0_5/ebit_z7010_top_axi_gpio_0_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebit_z7010_top_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ebit_z7010.gen/sources_1/bd/ebit_z7010_top/ip/ebit_z7010_top_axi_gpio_0_5/ebit_z7010_top_axi_gpio_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebit_z7010_top_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /mnt/d/Xilinx/Projects/Vivado/Field-Oriented-Control-on-ZYNQ/ebit_z7010.gen/sources_1/bd/ebit_z7010_top/ip/ebit_z7010_top_axi_gpio_0_5/ebit_z7010_top_axi_gpio_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebit_z7010_top_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
