# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ebit_z7010-master/ip_repo/DPUCZDX8G_v3_3_0/xci/sfm/fp_exp/fp_exp.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_exp || ORIG_REF_NAME==fp_exp} -quiet] -quiet

# IP: d:/ebit_z7010-master/ip_repo/DPUCZDX8G_v3_3_0/xci/sfm/fp_div/fp_div.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_div || ORIG_REF_NAME==fp_div} -quiet] -quiet

# IP: d:/ebit_z7010-master/ip_repo/DPUCZDX8G_v3_3_0/xci/sfm/fp_convert/fp_convert.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_convert || ORIG_REF_NAME==fp_convert} -quiet] -quiet

# IP: d:/ebit_z7010-master/ip_repo/DPUCZDX8G_v3_3_0/xci/sfm/fp_add/fp_add.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# IP: d:/ebit_z7010-master/ip_repo/DPUCZDX8G_v3_3_0/xci/sfm/fp_acc/fp_acc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_acc || ORIG_REF_NAME==fp_acc} -quiet] -quiet
