# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pawel5sekund/VivadoProjects/EBAZ4205/ip_repo/FOC_BLDC/FOC_BLDC.srcs/sources_1/ip/MULTIPLY_DSP/MULTIPLY_DSP.xci
# IP: The module: 'MULTIPLY_DSP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pawel5sekund/VivadoProjects/EBAZ4205/ip_repo/FOC_BLDC/FOC_BLDC.gen/sources_1/ip/MULTIPLY_DSP/MULTIPLY_DSP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MULTIPLY_DSP'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/pawel5sekund/VivadoProjects/EBAZ4205/ip_repo/FOC_BLDC/FOC_BLDC.srcs/sources_1/ip/MULTIPLY_DSP/MULTIPLY_DSP.xci
# IP: The module: 'MULTIPLY_DSP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pawel5sekund/VivadoProjects/EBAZ4205/ip_repo/FOC_BLDC/FOC_BLDC.gen/sources_1/ip/MULTIPLY_DSP/MULTIPLY_DSP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MULTIPLY_DSP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
